version: "3.4"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db_vol:/var/lib/mysql:rw

  backend:
    container_name: 'backendserver'
    image: nadinemilli/achat
    ports:
      - '8089:8089'
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysqldb

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - common-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
      - grafana_plugins:/var/lib/grafana/plugins
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - common-net

volumes:
  db_vol:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
  prometheus_config:
  prometheus_data:
  grafana_data:
  grafana_config:
  grafana_plugins:

networks:
  common-net:
    driver: bridge
